#!/usr/bin/env bash

# Install extensions
code --install-extension aaron-bond.better-comments
code --install-extension alefragnani.bookmarks
code --install-extension bierner.markdown-preview-github-styles
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dakara.transformer
code --install-extension dbaeumer.vscode-eslint
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension vscode-icons-team.vscode-icons

# Symlink user settings file
ln -sf ~/dotfiles/vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json
