#!/bin/zsh

code --install-extension dakara.transformer
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-british-english
code --install-extension vscode-icons-team.vscode-icons

ln -sf ~/.dotfiles/vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json
