#!/bin/zsh

# Installs common applications and tools using Homebrew

# Install Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Tap homebrew-cask-versions  
brew tap homebrew/cask-versions

# Install packages
brew install exiftool
brew install git
brew install openssl
brew install svn
brew install tree
brew install wget

# Install apps
brew install --cask alfred
# brew install --cask discord
# brew install --cask firefox
# brew install --cask firefox-developer-edition
brew install --cask google-chrome
brew install --cask iterm2
brew install --cask rar
brew install --cask rectangle
# brew install --cask sequel-pro
# brew install --cask transmit
brew install --cask visual-studio-code

# Install fonts
brew tap homebrew/cask-fonts
brew install --cask font-source-code-pro
